CREATE TABLE `AccumulatePayScore` (
  `uid` BIGINT UNSIGNED NOT NULL,
  `season_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `group_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `score` INT UNSIGNED NOT NULL DEFAULT 0,
  `days` INT UNSIGNED NOT NULL DEFAULT 0,
  `last_score_day` INT UNSIGNED NOT NULL DEFAULT 0,
  `score_rewards` BLOB NULL DEFAULT NULL,
  `gold` INT UNSIGNED NOT NULL DEFAULT 0,
  `pay_rewards` BLOB NULL DEFAULT NULL,
  `mtime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `ctime` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`uid`)
) ENGINE=InnoDB default charset=utf8;
