CREATE TABLE `DonationData` (
  `uid` BIGINT UNSIGNED NOT NULL,
  `type` SMALLINT UNSIGNED NOT NULL,
  `season_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `group_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `score` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `crit_list` BLOB NULL DEFAULT NULL,
  `reward_info` BLOB NULL DEFAULT NULL,
  `mtime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `ctime` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`uid`, `type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
