CREATE TABLE DragonSkill2 (
`uid` BIGINT UNSIGNED NOT NULL,
`parts_id` BIGINT UNSIGNED NOT NULL,
`group_id` BIGINT UNSIGNED NOT NULL,
`level` TINYINT UNSIGNED NOT NULL DEFAULT 0,
`star_level` TINYINT NOT NULL DEFAULT 0,
`skill_star_cost` BLOB COMMENT '升级技能星级消耗',
`item_cost` BLOB COMMENT '特殊技能升级物品消耗',
`ctime` TIMESTAMP NOT NULL DEFAULT 0,
`mtime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY ( `uid`, `group_id` )
) ENGINE = INNODB DEFAULT CHARSET = utf8;