CREATE TABLE `DragonKnightBenefit` (
     `uid` bigint unsigned NOT NULL,
     `col_1` blob,
     `col_2` blob,
     `col_3` blob,
     `col_4` blob,
     `col_5` blob,
     `col_6` blob,
     `col_7` blob,
     `col_8` blob,
     `col_9` blob,
     `col_10` blob,
     `col_11` blob,
     `col_12` blob,
     `col_13` blob,
     `col_14` blob,
     `col_15` blob,
     `col_16` blob,
     `col_17` blob,
     `col_18` blob,
     `col_19` blob,
     `col_20` blob,
     `col_21` blob,
     `col_22` blob,
     `col_23` blob,
     `col_24` blob,
     `col_25` blob,
     `col_26` blob,
     `col_27` blob,
     `col_28` blob,
     `col_29` blob,
     `col_30` blob,
     `col_31` blob,
     `col_32` blob,
     `col_33` blob,
     `col_34` blob,
     `col_35` blob,
     `col_36` blob,
     `col_37` blob,
     `col_38` blob,
     `col_39` blob,
     `col_40` blob,
     `col_41` blob,
     `col_42` blob,
     `col_43` blob,
     `col_44` blob,
     `col_45` blob,
     `col_46` blob,
     `col_47` blob,
     `col_48` blob,
     `col_49` blob,
     `col_50` blob,
     `ctime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
     `mtime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
     PRIMARY KEY(uid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=Dynamic;
