CREATE TABLE `IapLuckyCard` (
  `uid` BIGINT UNSIGNED NOT NULL,
  `season_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `state` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  `reset_times` INT UNSIGNED NOT NULL DEFAULT 0,
  `pool_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `pool_data` BLOB NULL DEFAULT NULL,
  `mtime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `ctime` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`uid`)
) ENGINE = INNODB DEFAULT CHARSET utf8;
