CREATE TABLE `IapSingleRebate` (
  `uid` BIGINT UNSIGNED NOT NULL,
  `season_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `received` BLOB NULL DEFAULT NULL,
  `left_rewards` BLOB NULL DEFAULT NULL,
  `mtime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `ctime` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`uid`, `season_id`)
) ENGINE = INNODB DEFAULT CHARSET utf8;
