CREATE TABLE `KingsRoad` (
     `uid` BIGINT UNSIGNED NOT NULL,
     `activity_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
     `activity_group_id` INT UNSIGNED NOT NULL DEFAULT 0,
     `offset_register_time` BIGINT UNSIGNED NOT NULL DEFAULT 0,
     `refresh_quest_time` BIGINT UNSIGNED NOT NULL DEFAULT 0,
     `stashes` BLOB,
     `mtime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
     `ctime` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
     PRIMARY KEY (`uid`)
) ENGINE = INNODB DEFAULT CHARSET utf8;
