CREATE TABLE `KingdomQuestUserInstance` (
  `uid` BIGINT UNSIGNED NOT NULL,
  `slot_id` INT UNSIGNED NOT NULL,
  `quest_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `reward_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `state` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  `end_time` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  `mtime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `ctime` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`uid`, `slot_id`));