CREATE TABLE `LimitMotivatePayment` (
  `uid` BIGINT UNSIGNED NOT NULL,
  `push_id` BIGINT UNSIGNED NOT NULL,
  `push_num` INT UNSIGNED NOT NULL DEFAULT 0,
  `left_times` INT UNSIGNED NOT NULL DEFAULT 0,
  `start_time` TIMESTAMP NOT NULL,
  `end_time` TIMESTAMP NOT NULL,
  `pop_up` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  `mtime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `ctime` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`uid`, `push_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
