CREATE TABLE IF NOT EXISTS `MagicEnergyLadder` (
  `uid` bigint(20) UNSIGNED NOT NULL,
  `season_id` bigint(20) UNSIGNED NOT NULL,
  `score` bigint(20) UNSIGNED NOT NULL,
  `rank` bigint(20) UNSIGNED NOT NULL,
  `uncollected_score` bigint(20) UNSIGNED NOT NULL,
  `score_update_time` timestamp NOT NULL DEFAULT 0,
  `resources` blob,
  `collect_cd_time` timestamp NOT NULL DEFAULT 0,
  `defend_troops` blob,
  `defend_benefits` blob,
  `defend_troop_skills` blob,
  `defend_troop_skills_lv` blob,
  `defend_dragon` blob,
  `defend_legends` blob,
  `defend_pets` blob,
  `season_refresh_time` int UNSIGNED NOT NULL DEFAULT 0,
  `rivals` blob,
  `rob_results` blob,
  `refresh_cd_time` timestamp NOT NULL DEFAULT 0,
  `refresh_times` bigint(20) UNSIGNED NOT NULL DEFAULT 0,
  `attack_total_times` int UNSIGNED NOT NULL DEFAULT 0,
  `attack_win_times` int UNSIGNED NOT NULL DEFAULT 0,
  `defend_total_times` int UNSIGNED NOT NULL DEFAULT 0,
  `defend_win_times` int UNSIGNED NOT NULL DEFAULT 0,
  `last_score` int UNSIGNED NOT NULL DEFAULT 0,
  `last_daily_time` int UNSIGNED NOT NULL DEFAULT 0,
  `last_season_time` int UNSIGNED NOT NULL DEFAULT 0,
  `version` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `ctime` timestamp NOT NULL DEFAULT 0,
  `mtime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`uid`)
);