CREATE TABLE `NewMonthCard` (
  `uid` BIGINT UNSIGNED NOT NULL,
  `type` INT UNSIGNED NOT NULL,
  `card_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `tab_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `is_subscription` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `start_date` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  `end_date` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  `last_reward_day` INT UNSIGNED NOT NULL DEFAULT 0,
  `job_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `left_days` INT UNSIGNED NOT NULL DEFAULT 0,
  `reward_groups` BLOB NULL DEFAULT NULL,
  `benefits` BLOB NULL DEFAULT NULL,
  `subscription_benefits` BLOB NULL DEFAULT NULL,
  `buy_times` BLOB NULL DEFAULT NULL,
  `mtime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `ctime` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`uid`, `type`)
) ENGINE=InnoDB default charset=utf8;
