CREATE TABLE IF NOT EXISTS RoyalChampionshipsBattleReport (
  `uid` BIGINT UNSIGNED NOT NULL,
  `rival_uid` BIGINT UNSIGNED NOT NULL,
  `report_id` BIGINT UNSIGNED NOT NULL,
  `attacker` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `win` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `revenged` int UNSIGNED NOT NULL DEFAULT 0,
  `gain_info` BLOB NULL,
  `battle_log` MEDIUMBLOB NULL,
  `ctime` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  `mtime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`uid`, `rival_uid`, `report_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=Dynamic;