CREATE TABLE `StrengthProve` (
  `uid` BIGINT UNSIGNED NOT NULL,
  `season_id` BIGINT UNSIGNED DEFAULT 0,
  `stage` INT UNSIGNED DEFAULT 0,
  `progress` BLOB NULL DEFAULT NULL,
  `rewarded` BLOB NULL DEFAULT NULL,
  `mtime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `ctime` TIMESTAMP NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`uid`)
) ENGINE = INNODB DEFAULT CHARSET utf8;
