CREATE TABLE `ThirdPartyPaymentOrder` (
  `uid` BIGINT UNSIGNED NOT NULL,
  `order_id` CHAR(64) NOT NULL,
  `state` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  `data` BLOB NULL DEFAULT NULL,
  `mtime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `ctime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`uid`, `order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
