CREATE TABLE `UserBuff` (
  `uid` BIGINT UNSIGNED NOT NULL,
  `type` INT UNSIGNED NOT NULL,
  `buff_id` BIGINT UNSIGNED NOT NULL,
  `trace` INT UNSIGNED NOT NULL DEFAULT 0,
  `job_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `use_times` INT UNSIGNED NOT NULL DEFAULT 0,
  `mtime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `ctime` TIMESTAMP NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`uid`, `type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
