CREATE TABLE `UserTroop` (
 `uid` BIGINT UNSIGNED NOT NULL,
 `kid` INT UNSIGNED NOT NULL,
 `sky_hospital` BLOB,
 `mtime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 `ctime` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
PRIMARY KEY (`uid`, `kid`));
