CREATE TABLE UserInfo  (
    uid bigint unsigned NOT NULL DEFAULT 0,
    world_id bigint unsigned NOT NULL DEFAULT 0 COMMENT "also known as kingdom id",
    current_world_id bigint unsigned NOT NULL DEFAULT 0 COMMENT "current kingdom id",
    last_world_id bigint unsigned NOT NULL DEFAULT '0' COMMENT "last kingdom id",
    alliance_id bigint UNSIGNED NOT NULL DEFAULT 0 COMMENT "Which alliance the user belongs to",
    team_id bigint UNSIGNED NOT NULL DEFAULT 0 COMMENT "team id instead of alliance_id if need",
    name varchar(100) DEFAULT NULL COMMENT "This is the player name",
    power bigint unsigned NOT NULL DEFAULT 0 COMMENT "Numerical representation of the SUM of troops and troop level, building and building level as well as quests completed",
    max_power bigint unsigned NOT NULL DEFAULT 0,
    lord_power bigint(20) unsigned NOT NULL DEFAULT 0,
    dragon_power bigint(20) unsigned NOT NULL DEFAULT 0,
    troops_power bigint(20) unsigned NOT NULL DEFAULT 0,
    building_power bigint(20) unsigned NOT NULL DEFAULT 0,
    research_power bigint(20) unsigned NOT NULL DEFAULT 0,
    trap_power bigint(20) unsigned NOT NULL DEFAULT 0,
    legend_power bigint(20) unsigned NOT NULL DEFAULT 0,
    legend_attr_power bigint(20) unsigned NOT NULL DEFAULT 0,
    equip_power bigint unsigned NOT NULL DEFAULT 0,
    dk_equip_power bigint unsigned NOT NULL DEFAULT 0,
    tactics_power bigint unsigned NOT NULL DEFAULT 0,
    troop_skill_power bigint unsigned NOT NULL DEFAULT 0,
    pet_power bigint unsigned NOT NULL DEFAULT 0,
    dominate_power blob,
    combat_research_power bigint(20) unsigned NOT NULL DEFAULT 0,
    poseidon_power bigint(20) unsigned NOT NULL DEFAULT 0,
    gem_power bigint(20) unsigned NOT NULL DEFAULT 0,
    real_equip_power bigint(20) unsigned NOT NULL DEFAULT 0,
    max_equip_power bigint(20) unsigned NOT NULL DEFAULT 0,
    max_gem_power bigint(20) unsigned NOT NULL DEFAULT 0,
    escape_tool_power bigint(20) unsigned NOT NULL DEFAULT 0,
    gold bigint unsigned NOT NULL DEFAULT 0 COMMENT "How much premium currency the user has",
    diamond bigint unsigned NOT NULL DEFAULT 0,
    normal_gold bigint unsigned NOT NULL DEFAULT 0,
    hidden_gold bigint unsigned NOT NULL DEFAULT 0,
    world_auction_gold BIGINT UNSIGNED NOT NULL DEFAULT 0,
    hold_gold blob,
    steel bigint unsigned NOT NULL DEFAULT 0 COMMENT "How much steel the user has",
    honor bigint unsigned NOT NULL DEFAULT 0 COMMENT "Alliance currency",
    `valor_coin` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '英灵币',
    copper_coin bigint unsigned NOT NULL DEFAULT 0 COMMENT "掷距骨数量",
    dragon_coin bigint unsigned NOT NULL DEFAULT 0 COMMENT "符文石数量",
    merlin_coin bigint unsigned NOT NULL DEFAULT 0,
    emblem_essence bigint unsigned NOT NULL DEFAULT 0 COMMENT "巨龙印记精华",
    essence bigint unsigned NOT NULL DEFAULT '0' COMMENT "Blacksmith currency",
    chat_channel bigint unsigned NOT NULL DEFAULT 0,
    inventory_slots smallint unsigned NOT NULL DEFAULT 0 COMMENT " How many slots are in the inventory",
    gift_mode tinyint unsigned NOT NULL DEFAULT 0 COMMENT "gift mode",
    daily_streak blob,
    daily_point blob COMMENT '日常奖励积分 {"start":1447039937,"point":20,"chests":[1,2,3]}',
    portrait varchar(200) NOT NULL DEFAULT '0' COMMENT "player portrait",
    unlock_portrait blob,
    icon varchar(200) NOT NULL DEFAULT '' COMMENT "player upload portrait",
    icon_cd timestamp NOT NULL DEFAULT 0,
    vip_points int unsigned NOT NULL default 0,
    vip_job_id bigint unsigned DEFAULT 0 COMMENT "vip life cycle",
    tutorial blob,
    signature varchar(300) NOT NULL default '',
    monster_level tinyint unsigned NOT NULL DEFAULT 0 COMMENT "PVE最高等级限制",
    language varchar(50) NOT NULL DEFAULT 'en' COMMENT "玩家语言",
    last_login timestamp NOT NULL DEFAULT 0 COMMENT "最后登录时间",
    last_last_login timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT "上上次登录时间",
    notification_config blob,
    anti_disturb_config blob,
    push_service VARCHAR(20) NOT NULL,
    setting blob,
    fpid bigint NOT NULL COMMENT 'funplus ID',
    title bigint unsigned NOT NULL DEFAULT 0 COMMENT "title id",
    lord_title bigint unsigned NOT NULL DEFAULT 0 COMMENT "active lord title id",
    total_pay FLOAT NOT NULL DEFAULT 0 COMMENT '用户总支付',
    is_pay tinyint(3) NOT NULL DEFAULT '-1' COMMENT '是否支付用户不包括购买月卡',
    data_reset_ver VARCHAR(10) NOT NULL DEFAULT '' COMMENT '登陆时数据重置版本号',
    pkg_channel VARCHAR(128) NOT NULL DEFAULT '' COMMENT '玩家的首次安装来自哪个渠道包',
    `suspect` tinyint(2) NOT NULL DEFAULT 0,
    ac_group_id INT NOT NULL COMMENT '联盟战分组id',
    ac_alliance_id BIGINT NOT NULL COMMENT '联盟战联盟id',
    ac_end_time TIMESTAMP DEFAULT 0 NOT NULL COMMENT '联盟战结束时间',
    `policies` BLOB COMMENT '用户协议: {policy_id => {stat: 0/1, time: timestamp}}',
    migrate_info blob,
    `change_world_time` timestamp NULL COMMENT '上次迁服时间',
    `seed` bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT '随机种子',
    sign_ver VARCHAR(10) NOT NULL DEFAULT '' COMMENT '注册时版本号',
    `deleted` tinyint(2) DEFAULT '0' COMMENT '是否删除账号',
    ctime timestamp NOT NULL DEFAULT 0,
    mtime timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    tutorial_z blob,
    PRIMARY KEY (uid)
) ENGINE = INNODB DEFAULT CHARSET utf8;
