CREATE TABLE UserTactics (
  `uid` BIGINT UNSIGNED NOT NULL,
  `total_book` INT UNSIGNED NOT NULL DEFAULT 0,
  `current_book` INT UNSIGNED NOT NULL DEFAULT 0,
  `book_job_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `mtime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `ctime` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`uid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;