CREATE TABLE `UserKingdomMail` (
    `uid` bigint unsigned NOT NULL,
    `mail_id` bigint unsigned NOT NULL,
    `from_portrait` varchar(200) NOT NULL DEFAULT '' COMMENT "系统头像",
    `from_icon` varchar(200) NOT NULL DEFAULT '',
    `title` blob COMMENT "{key:***,params:[]}",
    `body` MEDIUMBLOB COMMENT "{key:***,params:[]}",
    `data` blob COMMENT "邮件展示所需json格式数据",
    `category` tinyint unsigned NOT NULL DEFAULT 0 COMMENT "邮件的大类",
    `type` int unsigned NOT NULL DEFAULT 0 COMMENT "邮件的小类",
    `status` tinyint unsigned NOT NULL DEFAULT 0 COMMENT "1:表示已读",
    `favorite` tinyint unsigned NOT NULL DEFAULT 0 COMMENT "1:表示收藏",
    `attachment` blob COMMENT "邮件附件",
    `attachment_expiration_time` timestamp NOT NULL DEFAULT 0 COMMENT "邮件附件过期时间",
    `attachment_status` tinyint unsigned NOT NULL DEFAULT 0,
    `ctime` timestamp NOT NULL DEFAULT 0,
    `mtime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`uid`,`mail_id`),
    KEY `idx_ctime` (`ctime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
