CREATE TABLE `UserRawRow` (
  `uid` BIGINT UNSIGNED NOT NULL,
  `_type` INT UNSIGNED NOT NULL,
  `_content` BLOB NULL,
  `mtime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `ctime` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`uid`, `_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=Dynamic;