CREATE TABLE `UserProfile`(
    `uid` bigint unsigned NOT NULL DEFAULT 0,
    `battles_won` int unsigned NOT NULL DEFAULT 0 COMMENT "战斗胜利总数",
    `battles_lost` int unsigned NOT NULL DEFAULT 0 COMMENT "战斗失败总数",
    `attack_won` int unsigned NOT NULL DEFAULT 0 COMMENT "进攻胜利总数",
    `attack_lost` int unsigned NOT NULL DEFAULT 0 COMMENT "进攻失败总数",
    `defense_won` int unsigned NOT NULL DEFAULT 0 COMMENT "防守胜利总数",
    `total_scout` int unsigned NOT NULL DEFAULT 0 COMMENT "侦查总数",
    `wars_won` int unsigned NOT NULL DEFAULT 0 COMMENT "warRally和防御warRally的胜利次数",
    `wars_lost` int unsigned NOT NULL DEFAULT 0 COMMENT "warRally和防御warRally的失败次数",
    `troops_killed` bigint unsigned NOT NULL DEFAULT 0 COMMENT "杀死敌军总数",
    `troops_hospitalized` bigint unsigned NOT NULL DEFAULT 0 COMMENT "将别人的部队送入医院的总数",
    `traps_destroyed` bigint unsigned NOT NULL DEFAULT 0 COMMENT "摧毁的陷阱数",
    `troops_lost` bigint unsigned NOT NULL DEFAULT 0 COMMENT "被杀死的部队数",
    `troops_healed` bigint unsigned NOT NULL DEFAULT 0 COMMENT "自己治愈了多少部队",
    `cities_destroyed` int unsigned NOT NULL DEFAULT 0 COMMENT "着火的城市数",
    `resources_collected` bigint unsigned NOT NULL DEFAULT 0 COMMENT "资源采集总数",
    `monsters_killed` int unsigned NOT NULL DEFAULT 0 COMMENT "杀死野怪数",
    `resource_sent` bigint unsigned NOT NULL DEFAULT 0 COMMENT "送给别人的资源数",
    `food_sent` bigint unsigned NOT NULL DEFAULT 0 COMMENT "送给别人的食物数",
    `silver_sent` bigint unsigned NOT NULL DEFAULT 0 COMMENT "送给别人的银币数",
    `wood_sent` bigint unsigned NOT NULL DEFAULT 0 COMMENT "送给别人的木头数",
    `ore_sent` bigint unsigned NOT NULL DEFAULT 0 COMMENT "送给别人的铁矿数",
    `alliance_help` int unsigned NOT NULL DEFAULT 0 COMMENT "联盟帮助的次数",
    `alliance_gifts_opened` int unsigned NOT NULL DEFAULT 0 COMMENT "打开过的联盟礼物次数",
    `consecutive_login_days` int unsigned NOT NULL DEFAULT 0 COMMENT "连续登录天数",
    `total_login_days` int unsigned NOT NULL DEFAULT 0 COMMENT "总登录天数",
    `mtime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (uid)
) ENGINE = INNODB DEFAULT CHARSET=utf8;
