CREATE TABLE DragonKnight (
    uid bigint unsigned NOT NULL DEFAULT 0,
    name varchar(100) DEFAULT NULL,
    xp bigint unsigned NOT NULL DEFAULT 0,
    level mediumint unsigned NOT NULL DEFAULT 0,
    gender varchar(1) NOT NULL DEFAULT 'm' COMMENT '性别, m 或者 f',
    talent_point bigint unsigned NOT NULL DEFAULT 0 COMMENT "天赋点",
    spirit bigint unsigned NOT NULL DEFAULT 0,
    equipment blob COMMENT "{type => equip_id}",
    equipment_suit BLOB NOT NULL COMMENT '套装个数 {suit_id => num}',
    capacity bigint unsigned NOT NULL DEFAULT 0 COMMENT "负重",
    bag_amount bigint unsigned NOT NULL DEFAULT 0 COMMENT "背包格子数",
    march_id bigint unsigned NOT NULL DEFAULT 0,
    benefits blob default NULL,
    active_talent blob COMMENT "talent_id => {active_time, job_id}",
    is_in_dungeon tinyint unsigned NOT NULL DEFAULT 0 COMMENT "是否在副本中",
    last_open_dungeon_time  timestamp NOT NULL DEFAULT 0 COMMENT "最后一次开启副本的时间",
    dungeon_end_time timestamp NOT NULL DEFAULT 0 COMMENT "当前副本的结束时间",
    dungeon_latest_chapter INT UNSIGNED NOT NULL DEFAULT 0 COMMENT "5.0新增，副本可玩最大章节",
    dungeon_latest_stage INT UNSIGNED NOT NULL DEFAULT 0 COMMENT "5.0新增，副本可玩最大关卡",
    dungeon_data BLOB DEFAULT NULL COMMENT '副本相关数据',
    spirit_update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '5.0新增，耐力更新时间',
    max_dungeon_level bigint unsigned NOT NULL DEFAULT 0 COMMENT "曾经打过的最大副本层级,决定玩家是否可以直接从某个10层开始",
    skill_slot blob default NULL COMMENT "[slot_id => [is_locked,skill_id]]",
    attribute blob default NULL COMMENT "属性 key=> value {str, int, sta, armpr, atk, def, fire_value, water_value...}",
    forge_job_id bigint unsigned DEFAULT 0 COMMENT "forge equip job id",
    uncollected_equip blob COMMENT "equip forged not collect",
    ctime timestamp NOT NULL DEFAULT 0,
    mtime timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (uid)
) ENGINE=INNODB DEFAULT CHARSET utf8;

