CREATE TABLE DragonKnightDungeon (
    uid bigint unsigned NOT NULL,
    current_level bigint unsigned NOT NULL,
    current_grid int unsigned NOT NULL,
    previous_grid int unsigned NOT NULL,
    maze blob default NULL,
    skill_slot blob default NULL COMMENT "[slot_id => skill_id]",
    force_quit_job_id bigint unsigned NOT NULL default 0,
    raid_job_id BIGINT UNSIGNED NOT NULL,
    raid_info BLOB NOT NULL,
    dk_attribute blob default NULL COMMENT "副本内龙骑士的 hp => amount, mp => amount",
    dk_items blob default NULL COMMENT "副本内龙骑士可以使用的道具",
    bag_info blob default NULL,
    buff_benefits blob default NULL,
    dungeon_buff blob default NULL COMMENT "副本内buff耐久 buff_id => amount",
    battle_buff blob default NULL COMMENT "talent_buff_id => amount",
    chapter int UNSIGNED NOT NULL DEFAULT 0 COMMENT "5.0新增，当前副本章节",
    stage int UNSIGNED NOT NULL DEFAULT 0 COMMENT "5.0新增，当前章节的关卡",
    level int UNSIGNED NOT NULL DEFAULT 0 COMMENT "5.0新增，当前关卡的层数",
    version int unsigned NOT NULL DEFAULT 0 COMMENT "副本版本号",
    ctime timestamp NOT NULL DEFAULT 0,
    mtime timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (uid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
