CREATE TABLE `EscapeTool` (
  `uid` BIGINT UNSIGNED NOT NULL,
  `id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `config_id` INT UNSIGNED NOT NULL,
  `level` INT UNSIGNED NOT NULL,
  `inlaid_gem` BLOB COMMENT '{slot_id => UserGem.id}',
  `material_info` blob COMMENT '挂机掉落',
  `mtime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `ctime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`uid`, `id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=Dynamic;