CREATE TABLE `InvasionUserHistory` (
   `uid` BIGINT UNSIGNED NOT NULL,
   `group_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
   `damage_records` BLOB,
   `ctime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   `mtime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
   PRIMARY KEY (`uid`, `group_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;