CREATE TABLE `KingsRoadQuest` (
  `uid` bigint(20) NOT NULL,
  `quest_id` INT UNSIGNED NOT NULL DEFAULT 0,
  `quest_type` VARCHAR(100) NOT NULL DEFAULT '',
  `state` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `progress` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `mtime` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `ctime` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`uid`, `quest_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
