CREATE TABLE `PaymentOrder` (
  `uid` BIGINT UNSIGNED NOT NULL,
  `order_id` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `state` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  `data` BLOB NULL DEFAULT NULL,
  `mtime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `ctime` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`uid`, `order_id`)
) ENGINE=InnoDB default charset=utf8;
