CREATE TABLE IF NOT EXISTS `RoyalChampionships` (
    `uid` bigint(20) UNSIGNED NOT NULL,
    `season_id` bigint(20) UNSIGNED NOT NULL,
    `score` bigint(20) UNSIGNED NOT NULL,
    `rank` bigint(20) UNSIGNED NOT NULL,
    `defend_data` blob,
    `defend_benefits` blob,
    `season_refresh_time` int UNSIGNED NOT NULL DEFAULT 0,
    `rivals` blob,
    `challenge_results` blob,
    `refresh_times` bigint(20) UNSIGNED NOT NULL DEFAULT 0,
    `challenge_times` bigint(20) UNSIGNED NOT NULL DEFAULT 0,
    `last_login_time` int UNSIGNED NOT NULL DEFAULT 0,
    `last_daily_time` int UNSIGNED NOT NULL DEFAULT 0,
    `last_n_day_info` blob,
    `last_season_time` int UNSIGNED NOT NULL DEFAULT 0,
    `is_hidden` int UNSIGNED NOT NULL DEFAULT 0,
    `region_id` int UNSIGNED NOT NULL DEFAULT 0,
    `last_score` bigint(20) UNSIGNED NOT NULL DEFAULT 0,
    `challenge_lineup` blob,
    `ctime` timestamp NOT NULL DEFAULT 0,
    `mtime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`uid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=Dynamic;
