CREATE TABLE `UserSeasonMap` (
  `uid` bigint(20) unsigned NOT NULL,
  `season_id` int(10) unsigned NOT NULL COMMENT '赛季id',
  `benefits` blob COMMENT '增益列表',
  `tech` blob COMMENT '科技数据',
  `resources` blob COMMENT '资源数据',
  `season_data` blob COMMENT '赛季扩展数据',
  `stats` blob COMMENT '赛季统计数据',
  `ultra_num` int(10) unsigned NOT NULL COMMENT '究极集结数',
  `ultra_update_time` int(10) unsigned NOT NULL COMMENT '究极集结更新时间',
  `score` int(10) unsigned NOT NULL COMMENT '赛季积分',
  `supply` int(10) unsigned NOT NULL COMMENT '补给数,万分比,实际除以一万',
  `last_supply_time` int(10) unsigned NOT NULL COMMENT '上次结算补给时间',
  `welfare_time` int(10) unsigned NOT NULL COMMENT '上次领取红利时间',
  `donates` int(10) unsigned NOT NULL COMMENT '可捐赠次数',
  `donate_recover_time` int(10) unsigned NOT NULL COMMENT '上次结算捐赠次数时间',
  `ctime` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `mtime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `season_group_id` int(10) unsigned NOT NULL COMMENT '赛季配置组id',
  `hospital` blob,
  `medicine` bigint(10) unsigned NOT NULL DEFAULT '0',
  `medicine_update_time` int(10) unsigned NOT NULL DEFAULT '0',
  `battle_score` int(10) unsigned NOT NULL DEFAULT '0',
  `hospital_job_id` bigint(20) NOT NULL DEFAULT '0',
  `last_refresh_shop_time` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `selling_goods` blob COMMENT '战功商店销售商品',
  `shop_refresh_times` int(10) unsigned NOT NULL DEFAULT '0',
  `score_rewards` blob,
  `day_build_score` int(10) unsigned NOT NULL DEFAULT '0',
  `last_build_score_time` int(10) unsigned NOT NULL DEFAULT '0',
  `season_io_cd` int(10) unsigned NOT NULL DEFAULT '0',
  `chapter_done` int(10) unsigned NOT NULL DEFAULT '0',
  `total_battle_score` int(10) unsigned NOT NULL DEFAULT '0',
  `org_world_id` int(10) unsigned NOT NULL DEFAULT '0',
  `org_world_x` int(10) unsigned NOT NULL DEFAULT '0',
  `org_world_y` int(10) unsigned NOT NULL DEFAULT '0',
  `season_kid` int(10) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`uid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=Dynamic;
