CREATE TABLE UserEvaluationScore (
  `uid` BIGINT(20) UNSIGNED NOT NULL,
  `expend_total` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
  `benefit_total` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
  `expend_skill` BIGINT(20) UNSIGNED NOT NULL,
  `benefit_skill` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
  `expend_inventory` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
  `benefit_inventory` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
  `expend_battle_inventory` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
  `benefit_battle_inventory` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
  `expend_economy_inventory` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
  `benefit_economy_inventory` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
  `expend_gem` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
  `benefit_gem` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
  `expend_building` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
  `benefit_building` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
  `expend_building_statue` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
  `benefit_building_statue` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
  `expend_glory_level` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
  `benefit_glory_level` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
  `expend_research` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
  `benefit_research` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
  `expend_combat_research` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
  `benefit_combat_research` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
  `expend_legend` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
  `benefit_legend` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
  `expend_legend_suit` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
  `benefit_legend_suit` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
  `expend_dragon_level` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
  `benefit_dragon_level` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
  `expend_dragon_skill` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
  `benefit_dragon_skill` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
  `expend_dragon_emblem` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
  `benefit_dragon_emblem` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
  `expend_dk_inventory` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
  `benefit_dk_inventory` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
  `expend_dk_gem` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
  `benefit_dk_gem` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
  `expend_avalon_artifacts` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
  `benefit_avalon_artifacts` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
  `expend_alliance_tech` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
  `benefit_alliance_tech` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
  `expend_title` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
  `benefit_title` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
  `expend_artifact` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
  `benefit_artifact` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
  `expend_smith_blessing` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
  `benefit_smith_blessing` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
  `expend_tactics` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
  `benefit_tactics` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
  `expend_dk_skill` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
  `benefit_dk_skill` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
  `expend_dk_talent` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
  `benefit_dk_talent` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
  `expend_vip` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
  `benefit_vip` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
  `benefit_subscription` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
  `expend_subscription` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
  `expend_dk_dungeon` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
  `benefit_dk_dungeon` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
  `benefit_parliament_hero_artifact` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
  `expend_parliament_hero_artifact` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
  `benefit_troop_skill` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0,
  `ctime` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `mtime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`uid`)
) ENGINE=INNODB DEFAULT CHARSET utf8;
