CREATE TABLE `UserBenefitPart2` (
  `uid` bigint unsigned NOT NULL,
  `nl1` blob COMMENT 'prop_hero_army_damage_increase_percent',
  `nl2` blob COMMENT 'prop_hero_army_damage_decrease_percent',
  `nl3` blob COMMENT 'prop_hero_cavalry_damage_increase_percent',
  `nl4` blob COMMENT 'prop_hero_cavalry_damage_decrease_percent',
  `nl5` blob COMMENT 'prop_hero_ranged_damage_increase_percent',
  `nl6` blob COMMENT 'prop_hero_ranged_damage_decrease_percent',
  `nl7` blob COMMENT 'prop_hero_infantry_damage_increase_percent',
  `nl8` blob COMMENT 'prop_hero_infantry_damage_decrease_percent',
  `nl9` blob COMMENT 'prop_hero_siege_damage_increase_percent',
  `nl10` blob COMMENT 'prop_hero_siege_damage_decrease_percent',
  `nl11` blob COMMENT 'prop_army_base_attack_percent',
  `nl12` blob COMMENT 'prop_army_base_defense_percent',
  `nl13` blob COMMENT 'prop_army_base_health_percent',
  `nl14` blob COMMENT 'prop_cavalry_base_attack_percent',
  `nl15` blob COMMENT 'prop_cavalry_base_defense_percent',
  `nl16` blob COMMENT 'prop_cavalry_base_health_percent',
  `nl17` blob COMMENT 'prop_ranged_base_attack_percent',
  `nl18` blob COMMENT 'prop_ranged_base_defense_percent',
  `nl19` blob COMMENT 'prop_ranged_base_health_percent',
  `nl20` blob COMMENT 'prop_infantry_base_attack_percent',
  `nl21` blob COMMENT 'prop_infantry_base_defense_percent',
  `nl22` blob COMMENT 'prop_infantry_base_health_percent',
  `nl23` blob COMMENT 'prop_siege_base_attack_percent',
  `nl24` blob COMMENT 'prop_siege_base_defense_percent',
  `nl25` blob COMMENT 'prop_siege_base_health_percent',
  `nl26` blob COMMENT 'prop_hero_skill_damage_increase_percent',
  `nl27` blob COMMENT 'prop_hero_skill_damage_decrease_percent',
  `nl28` blob COMMENT 'prop_hero_strength_base_value',
  `nl29` blob COMMENT 'prop_hero_strength_percent',
  `nl30` blob COMMENT 'prop_hero_strength_value',
  `nl31` blob COMMENT 'prop_hero_intelligence_base_value',
  `nl32` blob COMMENT 'prop_hero_intelligence_percent',
  `nl33` blob COMMENT 'prop_hero_intelligence_value',
  `nl34` blob COMMENT 'prop_hero_agility_base_value',
  `nl35` blob COMMENT 'prop_hero_agility_percent',
  `nl36` blob COMMENT 'prop_hero_agility_value',
  `nl37` blob COMMENT 'prop_hero_speed_base_value',
  `nl38` blob COMMENT 'prop_hero_speed_percent',
  `nl39` blob COMMENT 'prop_hero_speed_value',
  `nl40` blob COMMENT 'prop_hero_skill_crit_rate_base_value',
  `nl41` blob COMMENT 'prop_hero_skill_crit_rate_percent',
  `nl42` blob COMMENT 'prop_hero_skill_crit_rate_value',
  `nl43` blob COMMENT 'prop_hero_skill_crit_damage_rate_base_value',
  `nl44` blob COMMENT 'prop_hero_skill_crit_damage_rate_percent',
  `nl45` blob COMMENT 'prop_hero_skill_crit_damage_rate_value',
  `nl46` blob COMMENT 'prop_hero_lottery_normal_free_times_value',
  `nl47` blob COMMENT 'prop_hero_lottery_special_free_time_base_value',
  `nl48` blob COMMENT 'prop_hero_lottery_special_free_time_value',
  `nl49` blob COMMENT 'prop_hero_lottery_special_free_time_percent',
  `dg3`  blob COMMENT 'prop_city_defend_dragon_value',
  `dg4`  blob,
  `ten1` BLOB NULL DEFAULT NULL,
  `ten2` BLOB NULL DEFAULT NULL,
  `ten3` BLOB NULL DEFAULT NULL,
  `ten4` BLOB NULL DEFAULT NULL,
  `ten5` BLOB NULL DEFAULT NULL,
  `ten6` BLOB NULL DEFAULT NULL,
  `ten7` BLOB NULL DEFAULT NULL,
  `ten8` BLOB NULL DEFAULT NULL,
  `ten9` BLOB NULL DEFAULT NULL,
  `ten10` BLOB NULL DEFAULT NULL,
  `ten11` BLOB NULL DEFAULT NULL,
  `ten12` BLOB NULL DEFAULT NULL,
  `ten13` BLOB NULL DEFAULT NULL,
  `ten14` BLOB NULL DEFAULT NULL,
  `ten15` BLOB NULL DEFAULT NULL,
  `ten16` BLOB NULL DEFAULT NULL,
  `ten17` BLOB NULL DEFAULT NULL,
  `ten18` BLOB NULL DEFAULT NULL,
  `ten19` BLOB NULL DEFAULT NULL,
  `ten20` BLOB NULL DEFAULT NULL,
  `ten21` BLOB NULL DEFAULT NULL,
  `ten22` BLOB NULL DEFAULT NULL,
  `ten23` BLOB NULL DEFAULT NULL,
  `ten24` BLOB NULL DEFAULT NULL,
  `ten25` BLOB NULL DEFAULT NULL,
  `ten26` BLOB NULL DEFAULT NULL,
  `ten27` BLOB NULL DEFAULT NULL,
  `ten28` BLOB NULL DEFAULT NULL,
  `ten29` BLOB NULL DEFAULT NULL,
  `ten30` BLOB NULL DEFAULT NULL,
  `ten31` BLOB NULL DEFAULT NULL,
  `ten32` BLOB NULL DEFAULT NULL,
  `ten33` BLOB NULL DEFAULT NULL,
  `ten34` BLOB NULL DEFAULT NULL,
  `ten35` BLOB NULL DEFAULT NULL,
  `ten36` BLOB NULL DEFAULT NULL,
  `dit01` BLOB NULL DEFAULT NULL,
  `dit02` BLOB NULL DEFAULT NULL,
  `dit03` BLOB NULL DEFAULT NULL,
  `dit04` BLOB NULL DEFAULT NULL,
  `dit05` BLOB NULL DEFAULT NULL,
  `dit06` BLOB NULL DEFAULT NULL,
  `dit07` BLOB NULL DEFAULT NULL,
  `dit08` BLOB NULL DEFAULT NULL,
  `dit09` BLOB NULL DEFAULT NULL,
  `dit10` BLOB NULL DEFAULT NULL,
  `dit11` BLOB NULL DEFAULT NULL,
  `dit12` BLOB NULL DEFAULT NULL,
  `dit13` BLOB NULL DEFAULT NULL,
  `dit14` BLOB NULL DEFAULT NULL,
  `dit15` BLOB NULL DEFAULT NULL,
  `dit16` BLOB NULL DEFAULT NULL,
  `dit17` BLOB NULL DEFAULT NULL,
  `dit18` BLOB NULL DEFAULT NULL,
  `dit19` BLOB NULL DEFAULT NULL,
  `dit20` BLOB NULL DEFAULT NULL,
  `dit21` BLOB NULL DEFAULT NULL,
  `dit22` BLOB NULL DEFAULT NULL,
  `dit23` BLOB NULL DEFAULT NULL,
  `dit24` BLOB NULL DEFAULT NULL,
  `dit25` BLOB NULL DEFAULT NULL,
  `dit26` BLOB NULL DEFAULT NULL,
  `dit27` BLOB NULL DEFAULT NULL,
  `dit28` BLOB NULL DEFAULT NULL,
  `dit29` BLOB NULL DEFAULT NULL,
  `dit30` BLOB NULL DEFAULT NULL,
  `dit31` BLOB NULL DEFAULT NULL,
  `dit32` BLOB NULL DEFAULT NULL,
  `dit33` BLOB NULL DEFAULT NULL,
  `dit34` BLOB NULL DEFAULT NULL,
  `dit35` BLOB NULL DEFAULT NULL,
  `dit36` BLOB NULL DEFAULT NULL,
  `dit37` BLOB NULL DEFAULT NULL,
  `dit38` BLOB NULL DEFAULT NULL,
  `dit39` BLOB NULL DEFAULT NULL,
  `dit40` BLOB NULL DEFAULT NULL,
  `dit41` BLOB NULL DEFAULT NULL,
  `dit42` BLOB NULL DEFAULT NULL,
  `dit43` BLOB NULL DEFAULT NULL,
  `dit44` BLOB NULL DEFAULT NULL,
  `dit45` BLOB NULL DEFAULT NULL,
  `dit46` BLOB NULL DEFAULT NULL,
  `dit47` BLOB NULL DEFAULT NULL,
  `dit48` BLOB NULL DEFAULT NULL,
  `dit49` BLOB NULL DEFAULT NULL,
  `dit50` BLOB NULL DEFAULT NULL,
  `dit51` BLOB NULL DEFAULT NULL,
  `dit52` BLOB NULL DEFAULT NULL,
  `dit53` BLOB NULL DEFAULT NULL,
  `dit54` BLOB NULL DEFAULT NULL,
  `dit55` BLOB NULL DEFAULT NULL,
  `dit56` BLOB NULL DEFAULT NULL,
  `dit57` BLOB NULL DEFAULT NULL,
  `dit58` BLOB NULL DEFAULT NULL,
  `dit59` BLOB NULL DEFAULT NULL,
  `dit60` BLOB NULL DEFAULT NULL,
  `dit61` BLOB NULL DEFAULT NULL,
  `dit62` BLOB NULL DEFAULT NULL,
  `dit63` BLOB NULL DEFAULT NULL,
  `dit64` BLOB NULL DEFAULT NULL,
  `dit65` BLOB NULL DEFAULT NULL,
  `dit66` BLOB NULL DEFAULT NULL,
  `dit67` BLOB NULL DEFAULT NULL,
  `dit68` BLOB NULL DEFAULT NULL,
  `dit69` BLOB NULL DEFAULT NULL,
  `dit70` BLOB NULL DEFAULT NULL,
  `dit71` BLOB NULL DEFAULT NULL,
  `dit72` BLOB NULL DEFAULT NULL,
  `spd2` BLOB NULL DEFAULT NULL,
  `spd3` BLOB NULL DEFAULT NULL,
  `rdp2` BLOB NULL DEFAULT NULL,
  `bs20` BLOB NULL DEFAULT NULL,
  `pes1` BLOB NULL DEFAULT NULL,
  `pes2` BLOB NULL DEFAULT NULL,
  `pes3` BLOB NULL DEFAULT NULL,
  `ndt1` BLOB NULL DEFAULT NULL,
  `ndt2` BLOB NULL DEFAULT NULL,
  `ndt3` BLOB NULL DEFAULT NULL,
  `ndt4` BLOB NULL DEFAULT NULL,
  `hl6` BLOB NULL DEFAULT NULL,
  `asp6` BLOB NULL DEFAULT NULL,
  `xd1` BLOB NULL DEFAULT NULL,
  `xd2` BLOB NULL DEFAULT NULL,
  `xd3` BLOB NULL DEFAULT NULL,
  `xd4` BLOB NULL DEFAULT NULL,
  `xd5` BLOB NULL DEFAULT NULL,
  `xd6` BLOB NULL DEFAULT NULL,
  `xd7` BLOB NULL DEFAULT NULL,
  `xd8` BLOB NULL DEFAULT NULL,
  `xf1` BLOB NULL DEFAULT NULL,
  `xf2` BLOB NULL DEFAULT NULL,
  `xf3` BLOB NULL DEFAULT NULL,
  `xf4` BLOB NULL DEFAULT NULL,
  `xf5` BLOB NULL DEFAULT NULL,
  `xf6` BLOB NULL DEFAULT NULL,
  `xf7` BLOB NULL DEFAULT NULL,
  `xf8` BLOB NULL DEFAULT NULL,
  `uac1` BLOB NULL DEFAULT NULL,
  `uac2` BLOB NULL DEFAULT NULL,
  `ctime` timestamp NOT NULL DEFAULT 0,
  `mtime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY(uid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=Dynamic;
