CREATE TABLE UserTacticsSkill (
  `uid` BIGINT UNSIGNED NOT NULL,
  `id` BIGINT UNSIGNED NOT NULL,
  `level` INT UNSIGNED NOT NULL DEFAULT 0,
  `used_book` INT UNSIGNED NOT NULL DEFAULT 0,
  `mtime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `ctime` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`uid`, `id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;