CREATE TABLE `UserDevice` (
  `uid` bigint(20) NOT NULL AUTO_INCREMENT,
  `lang` varchar(25) NOT NULL,
  `os` varchar(50) NOT NULL DEFAULT '',
  `os_version` varchar(50) NOT NULL DEFAULT '',
  `device` varchar(50) NOT NULL,
  `device_lang` varchar(11) NOT NULL,
  `app_version` varchar(10) NOT NULL DEFAULT '',
  `social_id` varchar(50) NOT NULL DEFAULT '',
  `idfa` varchar(50) NOT NULL DEFAULT '',
  `idfv` varchar(50) NOT NULL DEFAULT '',
  `android_id` varchar(50) NOT NULL DEFAULT '',
  `imei` varchar(50) NOT NULL DEFAULT '',
  `install_device_id` varchar(50) NOT NULL DEFAULT '' comment '注册时设备id',
  `install_lang` varchar(50) NOT NULL DEFAULT '' comment '注册时设备语言',
  `payment_whitelist` varchar(255) NOT NULL DEFAULT '' comment '玩家使用过的语言',
  `shield` blob NOT NULL COMMENT '用户屏蔽规则存储',
  `gaid` varchar(50) NOT NULL DEFAULT '',
  `time_zone` varchar(10) NOT NULL DEFAULT '',
  `ip` varchar(15) NOT NULL,
  `channel` varchar(50) NOT NULL DEFAULT '',
  `ctime` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `mtime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `appsflyer_id` varchar(70) NOT NULL DEFAULT '',
  `oaid` varchar(70) NOT NULL DEFAULT '',
  `firebase_instance_id` varchar(128) NOT NULL DEFAULT '',
  `fp_device_id` varchar(128) NOT NULL DEFAULT '',
  `anon_id` varchar(128) NOT NULL DEFAULT '',
  PRIMARY KEY (`uid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;